server:
  port: ":8080"

jwt:
  secret: "super-secret-jwt-key-change-in-prod-2026"

database:
  url: "host=postgres user=postgres password=postgres dbname=camera_security port=5432 sslmode=disable"

log:
  level: "debug"   # debug, info, warn, error

smtp:
  host: "smtp.gmail.com"
  port: 587
  email: "phamngocan2412@gmail.com" # Replace with your email or env var
  password: "" # Replace with env var

redis:
  addr: "redis:6379"
  password: ""
  db: 0